-- ============================================
-- ADVANCED BANKING MANAGEMENT SYSTEM
-- DATABASE SEQUENCES
-- ============================================

CREATE SEQUENCE seq_role_id
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_user_id
START WITH 1001
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_customer_id
START WITH 2001
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_account_id
START WITH 3001
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_transaction_id
START WITH 4001
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_entry_id
START WITH 5001
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_beneficiary_id
START WITH 6001
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE seq_log_id
START WITH 7001
INCREMENT BY 1
NOCACHE
NOCYCLE;